#!/bin/bash
clear
echo " # facebook.com/virus.system007"
echo " # @rikkimartin.rin"
echo " # YT Exsyio Tech"
echo ""
echo -n "Enter your ip addres : "
read ip
clear
echo "	IP INFO "
echo " ______________________________"
curl -s http://ipinfo.io/$ip | sed "s/\"//g; s/^ $//g; s/\:/ :/g; s/readme.*//g" | tr -d '{}'

